### ISSUE TITLE
Revive Directives?

### ISSUE THREAD

**Issue by jmatsushita** [OxfordAbstracts/purescript-graphql-client#115]
Hello @roryc89

I'm wondering whether you think that reviving your Directives #114 PR makes sense? I realise it's a breaking change and makes the type signatures more involved, but I've been using it to implement the `@live` directive for [this approach](https://github.com/n1ru4l/graphql-live-query) which is an alternative to Apollo's `watchQuery` and [it works quite well](https://github.com/jmatsushita/purescript-graphql-client/pull/1).

Thanks for the great library!

Jun

**Comment by roryc89** [comment]
Hi @jmatsushita. Thanks for taking the time to fix up that PR and add to it. It's been a while since I've looked at that code so I can't remember why I originally decided not to merge my portion of it. I'll have a look this weekend.

**Comment by roryc89** [comment]
Done

**Comment by jmatsushita** [comment]
🎉 Awesome, thanks!
