### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by jim108dev** [OxfordAbstracts/purescript-graphql-client#12]
Hi! Thank you for sharing this library. 
I have noticed that
```graphql
"""A location in a connection that can be used for resuming pagination."""
scalar Cursor
```
gets translated to

```purescript
 -- | A location in a connection that can be used for resuming pagination.
newtype Cursor = CursorUNKNOWN!!!!
```
What is the solution to that? Not using Cursor?

**Comment by roryc89** [comment]
Hi @jim108dev . The current solution to this is to add `Cursor` to `externalTypes` in your codegen options. 
`externalTypes` should be an object that maps gql type names to their purs type and modules i.e: 

```js 
const codeGenOpts = {
  externalTypes: { 
    Cursor: {
      moduleName: 'MyProject.Data.Cursor',
      typeName: 'MyCursorType'
    }
  ...restOfOptions
}
```

I will be adding this to the documentation soon. At the moment the best place to look is in the codegen example in the examples subdirectory for reference on the codegen options.

As far as I am aware, the graphql spec does not specify how to handle scalars so I have left it up to the library user on how to handle any non standard scalars. Let me know if you think there is a sensible Cursor purs ADT I should add by default.

**Comment by jim108dev** [comment]
Ok thanks. I have used the PursScript function with
```purescript
...
  , externalTypes: fromFoldable [ Tuple "Cursor" { moduleName: "Types", typeName: "Cursor" } ]
```
As far as I can tell `ID`, is not defined although it is a default scalar type (https://graphql.org/learn/schema/#scalar-types).

**Comment by roryc89** [comment]
Closing in favour of https://github.com/OxfordAbstracts/purescript-graphql-client/issues/23
