### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by jim108dev** [OxfordAbstracts/purescript-graphql-client#16]
Hi! Just to make sure I am not using it wrong the whole time.
I know TypeScript GraphQL CodeGen translates schemes and documents, e.g. for a mutation `AddEmail.graphql` it will create a function `useAddEmailMutation` in `index.tsx`. For this library the workflow is: translate scheme into purs files and translate every query/mutation individually via herokuapp, right? Wouldn't I be beneficial to have a purs to gql converter then, in case I want to test the query in graphiql?

**Comment by roryc89** [comment]
The way we use it at Oxford Abstracts is like this:
1. On project build we generate purs schemas from our GraphQL schemas. 
2. When writing a query/mutation we will often use use graphiql and then convert it to purs using the the herokuapp (just copying and pasting). Or just write it straight in purs if we know how.

> Wouldn't I be beneficial to have a purs to gql converter then, in case I want to test the query in graphiql?

I agree. For our use cases, after type checking we tend to be fairly confident of the result. But I have an issue open for it here: 
https://github.com/OxfordAbstracts/gql-query-to-purs/issues/1

**Comment by roryc89** [comment]
Documentation added with workflow. Rest of issue can be handled by OxfordAbstracts/gql-query-to-purs#1
