### ISSUE TITLE
request same schema param twice? is this possible?

### ISSUE THREAD

**Issue by srghma** [OxfordAbstracts/purescript-graphql-client#26]
https://github.com/OxfordAbstracts/purescript-graphql-client/blob/a77e3a477ae3ea5e0f690bdb17982a9138aa205a/examples/1-simple/src/Main.purs#L19-L20

IIUC it's not possible to write

```
      queryGql "Widget names with id 1"
        { widgets: { id: 1 } =>> { name } 
        , widgets2: { id: 2 } =>> { name } 
        }
```

**Comment by roryc89** [comment]
To do this you can use the alias operator `:` from `GraphQL.Client.Alias` all together it would look like this. 
```purs 
import GraphQL.Client.Alias ((:))
queryGql "Widget names with id 1"
        { widgets: { id: 1 } =>> { name } 
        , widgets2: widgets : { id: 2 } =>> { name } 
        }
```

**Comment by srghma** [comment]
oh, yes, sorry)

then I don't see difference between libs

perhaps only code with this lib will be easier to understand because of record syntax instead of Applicatives or ado

**Comment by roryc89** [comment]
@srghma If that's all we can see I will add that for now. Shall I describe your package as using Applicatives/ado syntax then?

**Comment by srghma** [comment]
yes, that's the main difference

**Comment by roryc89** [comment]
@srghma I have added this and some other points at https://github.com/OxfordAbstracts/purescript-graphql-client#alternatives-to-this-package . I hope the comparison is fair but as I am not familiar with https://github.com/purescript-graphqlclient/purescript-graphqlclient I may have missed points out. Please let me know if there is anything you would like me to change or add.
