### ISSUE TITLE
`Simple.JSON` integration?

### ISSUE THREAD

**Issue by CGenie** [OxfordAbstracts/purescript-graphql-client#64]
Hello,

Thank you for the nice library. Our code uses `Simple.JSON` extensively (https://github.com/justinwoo/purescript-simple-json). It results in less (and simpler imho) code than with `Argonaut`.

I was thinking of integrating that with `GraphQL.Client`. I tried to modify the code of `GraphQL.Client.BaseClients.Affjax` similar to https://purescript-simple-json.readthedocs.io/en/latest/with-affjax.html. However the issue lies deeper in the fact that `QueryClient` has the type `Json` hardcoded.

I was wondering if there is a way out of this?

**Comment by roryc89** [comment]
without this the library doesn't know how what type to decode your responses. Also, creating a new client for each client will be bit slower and not allow client caching etc. (although for your use case this might not be important)

**Comment by CGenie** [comment]
Splendid, this works, thank you!

**Comment by CGenie** [comment]
Ah, just found out that `GraphQL.Client.Variables` has `WithVars` with `Json` hardcoded. Any idea how to migrate that one to `Simple.JSON`? I guess that would be more involved as it requires changing the `WithVars` type itself.
